### ISSUE TITLE
ssh (id = ) does not exist

### ISSUE THREAD

**Issue by AshleighGB** [antoineco/kOVHernetes#2]
Hi,

I keep getting this issue when trying to deploy kubernetes with this script.

 ```ssh (id = ) does not exist```

but nowhere in your docs does it state where I can get the ssh key id from..
tried just using the name I gave it in the manager > got error.
tried using the ID i got from logging into horizon > got same error.
I'm lost on where to find my ssh key id for this script.

can you help?

**Comment by antoineco** [comment]
Sure I can. This is described here: https://github.com/antoineco/kOVHernetes/blob/master/docs/configuration.md

> kovh project keys

Hope that helps!

**Comment by antoineco** [comment]
ping @Wareing. Did you figure it out?

**Comment by AshleighGB** [comment]
Yep. issue can be closed/resolved.

I’d not done something in the initial steps :)

On 12 Jan 2018, 09:18 +0000, Antoine Cotten <notifications@github.com>, wrote:

ping @Wareing<https://github.com/wareing>. Did you figure it out?
