### ISSUE TITLE
Use of deprecated annotation for critical pods

### ISSUE THREAD

**Issue by gavvvr** [antoineco/kOVHernetes#4]
I noticed in `1.9` docs that Rescheduler is deprecated
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#rescheduler-guaranteed-scheduling-of-critical-add-ons

There is a use of `scheduler.alpha.kubernetes.io/critical-pod` in this project. Consider replacing it with Pods priorities

**Comment by antoineco** [comment]
Priorities are an alpha feature as of Kubernetes 1.9, but I will certainly add this as a TODO for supporting Kubernetes 1.10. Thanks for pointing this out 👍
